name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint (ESLint)
        run: npm run lint

      - name: Prettier check
        run: npm run format:check

      - name: Stylelint
        run: npm run stylelint

      - name: Typecheck (UI package)
        run: npm run -w @xiaofeng19920506/ui typecheck

      - name: Build Storybook (UI package)
        run: npm run -w @xiaofeng19920506/ui build-storybook